version: '3'
networks:
  app_net_nginx:
    ipam:
      config:
        - subnet: 29.0.0.0/24

services:

  proxy:
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./conf/cert.crt:/etc/nginx/ssl/cert.crt
      - ./conf/key.key:/etc/nginx/ssl/key.key
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/logs:/var/log/nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      app_net_nginx:
        ipv4_address: 29.0.0.30
 
  
  
volumes:
  conf:

